"""Lean 4 proof generation for concrete finite traces.

Generates a Lean file that proves the Shear expansion matrix product
equals the claimed Φ(γ), verified by native_decide.
"""

from __future__ import annotations

from datetime import datetime, timezone


def _mat_tuple(matrix: list[list[int]]) -> str:
    return f"({matrix[0][0]}, {matrix[0][1]}, {matrix[1][0]}, {matrix[1][1]})"


def _compute_product(matrices: list[list[list[int]]]) -> list[list[int]]:
    """Compute product of 2x2 matrices in list form."""
    phi = [[1, 0], [0, 1]]
    for m in matrices:
        phi = [
            [
                phi[0][0] * m[0][0] + phi[0][1] * m[1][0],
                phi[0][0] * m[0][1] + phi[0][1] * m[1][1],
            ],
            [
                phi[1][0] * m[0][0] + phi[1][1] * m[1][0],
                phi[1][0] * m[0][1] + phi[1][1] * m[1][1],
            ],
        ]
    return phi


def export_lean(
    step_matrices: list[list[list[int]]],
    machine_name: str = "MachineRun",
) -> str:
    """Generate Lean 4 proof that matrix product = Φ(γ).

    Args:
        step_matrices: List of 2x2 matrices (one per shear factor).
        machine_name: Name for the Lean definitions.
    """
    generated_at = datetime.now(timezone.utc).isoformat()
    factors = [_mat_tuple(m) for m in step_matrices]
    phi = _compute_product(step_matrices)
    phi_tuple = _mat_tuple(phi)

    return f'''-- Auto-generated by adelic-tm
-- machine: {machine_name}
-- generated_at_utc: {generated_at}

import Std

abbrev Mat2 := Int × Int × Int × Int

def det : Mat2 → Int
| (a, b, c, d) => a * d - b * c

def mul : Mat2 → Mat2 → Mat2
| (a, b, c, d), (e, f, g, h) =>
  (a * e + b * g, a * f + b * h, c * e + d * g, c * f + d * h)

def factors : List Mat2 :=
  [{', '.join(factors)}]

def phi : Mat2 := factors.foldl mul (1, 0, 0, 1)

example : phi = {phi_tuple} := by native_decide
'''
